flowchart LR
  VCS["Version Control Systems (VCS)"] --> Local["Local (LVCS)"]
  VCS --> Centralized["Centralized (CVCS)"]
  VCS --> |<span style="padding:10px;color:#94e2d5;">Our focus for today</span>| Distributed["Distributed (DVCS)"]

  style VCS fill:#fab387,stroke:#1e1e2e,stroke-width:2px,color:#1e1e2e
  style Local fill:#a6e3a1,stroke:#1e1e2e,stroke-width:2px,color:#1e1e2e
  style Centralized fill:#f9e2af,stroke:#1e1e2e,stroke-width:2px,color:#1e1e2e
  style Distributed fill:#94e2d5,stroke:#1e1e2e,stroke-width:2px,color:#1e1e2e
