flowchart LR
  A1[Actor 1 or File 1] --> S[Stage or Index]
  A2[Actor 2 or File 2] --> S
  A3[Actor 3 or File 3] --> S
  S --> Spectators[Spectators or Git]

  style S fill:#fab387,stroke:#1e1e2e,stroke-width:2px,color:#1e1e2e
  style A3 fill:#a6e3a1,stroke:#1e1e2e,stroke-width:2px,color:#1e1e2e
  style A1 fill:#f9e2af,stroke:#1e1e2e,stroke-width:2px,color:#1e1e2e
  style A2 fill:#94e2d5,stroke:#1e1e2e,stroke-width:2px,color:#1e1e2e
  style Spectators fill:#94e2d5,stroke:#1e1e2e,stroke-width:2px,color:#1e1e2e
